### ISSUE TITLE
Authentication always returns ACCESS DENIED

### ISSUE THREAD

**Issue by sunojvijayan** [vladimirfedorov/auth-challenge-response#1]
I have copy pasted the examaple code.

 var express = require('express'),
     app = express(),
     cookieParser = require('cookie-parser'),
     bodyParser = require('body-parser'),
     auth = require('auth-challenge-response').auth(app, {
         secret: 'secret',
         checkPassword: checkPassword
     })

 // checkPassword computes password hash using 
 // the same method the client is expected to use
 function checkPassword(challenge, clientHash, cb) {
     // TODO:
     // 1. Select user password hash from the database (challenge.username)
     // 2. Compute the second hash using generated challenge (challenge.value)
     // 3. Compare with the received client data (clientHash)
     // 4. If hashes do not match, send error object with the callback function
     // auth.hash is PBDKF2 using SHA-1
     var challengeValue = challenge.value || '',
         serverHash = auth.hash(auth.hash('password', 'user-secret'), challengeValue)

```
 console.log("userName " + challenge.username);
 console.log("client " + clientHash);
 console.log("server " + serverHash);

 if (challenge.username === 'username' && clientHash === serverHash) {
     console.log("innnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn")
     cb()
 } else {
     cb({
         status: 403,
         message: 'ACCESS DENIED'
     })
 }
```

 }

 app.use(cookieParser())

 // Check authentication: checks that authentication data is still valid
 // and sets res.locals.authenticated variable
 app.get('*', auth.checkAuthentication)

 // auth.challenge sends challenge and secret to client:
 // { id: challengeId, username: username, secret: secret, value: challengeValue }
 app.get('/auth/challenge/', auth.challenge)

 // auth.authenticate authenticates user
 // Client sends challengeId and password hash in any format 
 // supproted by the auth-challenge-response
 // Examples:
 // Query: /auth/authenticate?id=123&hash=z80kh2n...
 // Body, to send with post request: POST /auth/authenticate with JSON body {"id":"123","hash":"z80kh2n..."}
 app.get('/auth/authenticate', auth.authenticate)
     // to support id and hash values in the req.params object:
     // app.get('/auth/authenticate/:id/:hash', auth.authenticate)

 // auth.logout destroys authentication data making 
 // client's token invalid
 // auth.logout checks cookies authToken variable, req.params.token and req.query.token in this order
 app.get('/auth/logout', auth.logout)

 // auth.check sends status of authentication (JSON, {valid: true/false})
 // auth.check checks cookies authToken variable, req.params.token and req.query.token in this order
 app.get('/auth/check', auth.check)

 app.get('/', function (req, res, next) {
     // Authentication result is available in res.locals.authenticated 
     var authenticated = res.locals.authenticated

```
 // ...
```

 })

 app.listen(3945, function () {
     var host = this.address().address
     var port = this.address().port
     console.log('Listening at http://%s:%s', host, port)
 })

And started the server. and took url http://localhost:3945/auth/challenge

Shows 
{"id":6898063670378178,"secret":"secret","value":"qv597lh3q8gscgk4okc8sckowgs0cwk44os04wos4ssok4wks8"}

Now in a browser I type
http://localhost:3945/auth/authenticate?username=username&id=6898063670378178&hash=qv597lh3q8gscgk4okc8sckowgs0cwk44os04wos4ssok4wks8

But I am getting 
"status":403,"message":"ACCESS DENIED"}

Am I doing anything wrong. Please help?

**Comment by vladimirfedorov** [comment]
Hi sunojvijayan,
sorry for making you wait so long; in case you still have the problem with the function, client should implement the same hashing function the server does. In this case 
`serverHash = auth.hash(auth.hash('password', 'user-secret'), challengeValue)`
Here hash is computed in 2 steps: 
1) hash1 = PBKDF2 function from password and secret
2) hash2 = PBKDF2 function from hash1 and challenge
I attached a demo project that implements hashing on client side, please take a look at client.html. Hope this helps.
[auth.zip](https://github.com/vladimirfedorov/auth-challenge-response/files/277914/auth.zip)

**Comment by sunojvijayan** [comment]
Thanks a lot.
